config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :events
  resources :charges
  resources :attendances
  resources :events do
  	resources :attendances, only: [:new, :create]
  end
  resources :users, only: [:show] do
    resources :avatars, only: [:create]
  end
  root 'events#index'
  get 'events/index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
    belongs_to :user
    belongs_to :event
end

app/models/event.rb
class Event < ApplicationRecord
  after_create :subscribe_event_mail
  belongs_to :user
  has_many :attendances
  has_many :users, through: :attendances

  validates :duration, presence: true, numericality: true, if: :multiple_of_five?
  validates :title, presence: true, length: { in: 5..140 }
  validates :description, presence: true, length: { in: 20..1000 }
  validates :price, presence: true,  :inclusion => 0..1000
  validates :location, presence: true

  def multiple_of_five?
    res = self.duration % 5
     if res.positive?
       errors.add(:base, 'erreur date de durée')
       false
     end
  end

  def subscribe_event_mail
    UserMailer.subscribe_mail(self).deliver_now
  end

  def is_free?
    self.price == 0
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    after_create :welcome_send

    has_many :attendances
    has_many :events, through: :attendances
    
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                      format: { with: VALID_EMAIL_REGEX },
                      uniqueness: true
    validates :first_name, presence: true, length: { minimum: 3 }
    validates :last_name, presence: true, length: { minimum: 3 }

    has_one_attached :avatar
    def welcome_send
        UserMailer.welcome_email(self).deliver_now
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_devise_parameters, if: :devise_controller?

    def configure_devise_parameters
        devise_parameter_sanitizer.permit(:sign_up) {|u| u.permit(:first_name, :last_name, :is_alive, :email, :password, :password_confirmation)}
        devise_parameter_sanitizer.permit(:account_update) {|u| u.permit(:first_name, :last_name, :is_alive, :email, :password, :password_confirmation)}
    end
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :show, :edit, :destroy]

  def new
    @event_id = Event.find(params[:event_id])
    @attendance = Attendance.new
  end

  def create
    @event_id = Event.find(params[:event_id])
    @attendance = Attendance.new(user: current_user, event: @event_id)
    if @attendance.save
      redirect_to @attendance, notice: "Bravo! Youre set to go"
    else
      render :new
    end
  end

  def show
    @attendance = Attendance.find(params[:id])
  end

  def edit
  end

end

app/controllers/avatars_controller.rb
class AvatarsController < ApplicationController
    def create
        @user = User.find(params[:user_id])
        @user.avatar.attach(params[:avatar])
        redirect_to(user_path(@user))
    end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
  end
  
  def create
    # Amount in cents
    @amount = 500
  
    customer = Stripe::Customer.create({
      email: params[:stripeEmail],
      source: params[:stripeToken],
    })
  
    charge = Stripe::Charge.create({
      customer: customer.id,
      amount: @amount,
      description: 'Rails Stripe customer',
      currency: 'usd',
    })
  
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :show, :edit, :destroy]

  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def edit
    @event = find_event
  end

  def update
    @event = find_event
    @event.update(events_params)
    redirect_to @event
  end

  def show
    @event = find_event
  end

  def destroy
    @event = find_event
    @event.delete
    redirect_to '/'
  end

  def create
    @event = Event.new(events_params)
    @event.user = current_user
    if @event.save
      redirect_to @event, notice: "Bravo! You created a new event"
    else
      render :new
    end
  end

  private

  def events_params
    params.require(:event).permit(:title, :start_date, :duration, :description, :price, :location)
  end

  def find_event
    @event = Event.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!, only: [:show]

    def show
        @user = User.find(params[:id])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/avatars_helper.rb
module AvatarsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/attendances/edit.html.erb
<h1>Attendances#edit</h1>
<p>Find me in app/views/attendances/edit.html.erb</p>

app/views/attendances/index.html.erb
<div class="container justify-content-center ">
  <div class="row text-center">
    <div class="col-md-6 offset-md-3">
        <% current_user.events.each do |e| %>
            Evenement : <%= e.title %>
            <%= link_to '(Delete)', event_path(e), method: :delete, data: {confirm: 'Are you sure?'}%>
            | 
            <%= link_to '(edit)', edit_event_path(e)%>
            <p> - 
            <% e.users.each do |u| %>
                <%= u.first_name %>, 
            <% end %>
            </p>
        <% end %>
    </div>
  </div>
</div>

app/views/attendances/new.html.erb
<div class="container justify-content-center ">
  <div class="row text-center">
    <div class="col-md-6 offset-md-3">
        <%= form_tag event_attendances_path(params[:event_id]) do %>
        <article>
            <% if flash[:error].present? %>
            <div id="error_explanation">
                <p><%= flash[:error] %></p>
            </div>
            <% end %>
            <label class="amount">
            <span>Amount: <%= @event_id.price %> $</span>
            </label>
        </article>

        <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
                data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                data-description="Subscription à un event"
                data-amount="<%= @event_id.price%>"
                data-currency="eur"
                data-locale="auto"></script>
        <% end %>
    </div>
  </div>
</div>

app/views/attendances/show.html.erb
<div class="container justify-content-center ">
  <div class="row text-center">
    <div class="col-md-6 offset-md-3">
        <p> Subscribed </p>
    </div>
  </div>
</div>

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>
<p>
    <%= link_to 'See all event', '/'%>
</p>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: $5.00</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="500"
          data-locale="auto"></script>
<% end %>

app/views/events/edit.html.erb
<div class="container">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <%= form_for @event do |f| %>
      <% if @event.errors.any? %>
      <h4><%= pluralize(@event.errors.count, "error") %> prevented this message from saving</h4>
        <ul>
          <% @event.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
            <% end %>
        </ul>
        <% end %>
    <div class="form-group">
        <label>Titre de l'event </label>
        <%= f.text_field :title, class: 'form-control'%>
    </div>
    <div class="form-group">
        <label>Date de l'event</label>
        <%= f.date_field :start_date, class: 'form-control'%>
    </div>
    <div class="form-group">
        <label>Durée de l'event</label>
        <%= f.number_field :duration, class: 'form-control'%>
    </div>
    <div class="form-group">
        <label>Description de l'event</label>
        <%= f.text_area :description, class: 'form-control'%>
    </div>
    <div class="form-group">
        <label>Prix</label>
        <%= f.text_field :price, class: 'form-control'%>
    </div>
    <div class="form-group">
        <label>Localisation</label>
        <%= f.text_field :location, class: 'form-control'%>
    </div>
        <div class="form-group">
        <button type="submit" class="btn btn-primary">Valider</button>
    </div>
    <% end %>
</div>

app/views/events/index.html.erb
    <div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center bg-light">
      <div class="col-md-5 p-lg-5 mx-auto my-5">
        <h1 class="display-4 font-weight-normal">Create your event</h1>
        <p class="lead font-weight-normal">If you create it, they will come. Create an event and invite people!</p>
        <%= link_to "Create NOW", new_event_path, class: "btn btn-outline-secondary" %>
      </div>
      <div class="product-device box-shadow d-none d-md-block"></div>
      <div class="product-device product-device-2 box-shadow d-none d-md-block"></div>
    </div>

<% @events.each_slice(2) do |event| %>
    <% if event.last.id != event.first.id%>
    <div class="d-md-flex flex-md-equal w-100 my-md-3 pl-md-3">
      <div class="bg-dark mr-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center text-white overflow-hidden">
        <img class="card-img-top" src="https://picsum.photos/id/<%= rand(1..99) %>/500/230" alt="Card image cap">
        <div class="my-3 py-3">
          <h2 class="display-5"><%= event.first.title %></h2>
          <p class="lead"><%= event.first.description %></p>
        </div>
          <%= link_to "See Event", event_path(event.first, class: "btn btn-outline-secondary") %>
      </div>
      <div class="bg-light mr-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center overflow-hidden">
        <img class="card-img-top" src="https://picsum.photos/id/<%= rand(1..99) %>/500/230" alt="Card image cap">
        <div class="my-3 p-3">
          <h2 class="display-5"><%= event.last.title %></h2>
          <p class="lead"><%= event.last.description %></p>
        </div>
          <%= link_to "See Event", event_path(event.first, class: "btn btn-outline-secondary") %>
      </div>
    </div>
    <% else %>
      <div class="">
        <div class="d-md-flex flex-md-equal w-100 my-md-3 pl-md-3">
        <div class="bg-dark mr-md-3 pt-3 px-3 pt-md-5 px-md-5 text-center text-white overflow-hidden">
          <img class="card-img-top" src="https://picsum.photos/id/<%= rand(1..99) %>/500/230" alt="Card image cap">
          <div class="my-3 py-3">
            <h2 class="display-5"><%= event.first.title %></h2>
            <p class="lead"><%= event.first.description %></p>
          </div>
            <%= link_to "See Event", event_path(event.first, class: "btn btn-outline-secondary") %>
        </div>
      </div>
    <% end %>
<% end %>





    <footer class="container py-5">
      <div class="row">
        <div class="col-12 col-md">
          <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="d-block mb-2"><circle cx="12" cy="12" r="10"></circle><line x1="14.31" y1="8" x2="20.05" y2="17.94"></line><line x1="9.69" y1="8" x2="21.17" y2="8"></line><line x1="7.38" y1="12" x2="13.12" y2="2.06"></line><line x1="9.69" y1="16" x2="3.95" y2="6.06"></line><line x1="14.31" y1="16" x2="2.83" y2="16"></line><line x1="16.62" y1="12" x2="10.88" y2="21.94"></line></svg>
          <small class="d-block mb-3 text-muted">&copy; 2020-2021</small>
        </div>
        <div class="col-6 col-md">
          <h5>Features</h5>
          <ul class="list-unstyled text-small">
            <li><a class="text-muted" href="#">Cool stuff</a></li>
            <li><a class="text-muted" href="#">Random feature</a></li>
            <li><a class="text-muted" href="#">Team feature</a></li>
            <li><a class="text-muted" href="#">Stuff for developers</a></li>
            <li><a class="text-muted" href="#">Another one</a></li>
            <li><a class="text-muted" href="#">Last time</a></li>
          </ul>
        </div>
        <div class="col-6 col-md">
          <h5>Resources</h5>
          <ul class="list-unstyled text-small">
            <li><a class="text-muted" href="#">Resource</a></li>
            <li><a class="text-muted" href="#">Resource name</a></li>
            <li><a class="text-muted" href="#">Another resource</a></li>
            <li><a class="text-muted" href="#">Final resource</a></li>
          </ul>
        </div>
        <div class="col-6 col-md">
          <h5>Resources</h5>
          <ul class="list-unstyled text-small">
            <li><a class="text-muted" href="#">Business</a></li>
            <li><a class="text-muted" href="#">Education</a></li>
            <li><a class="text-muted" href="#">Government</a></li>
            <li><a class="text-muted" href="#">Gaming</a></li>
          </ul>
        </div>
        <div class="col-6 col-md">
          <h5>About</h5>
          <ul class="list-unstyled text-small">
            <li><a class="text-muted" href="#">Team</a></li>
            <li><a class="text-muted" href="#">Locations</a></li>
            <li><a class="text-muted" href="#">Privacy</a></li>
            <li><a class="text-muted" href="#">Terms</a></li>
          </ul>
        </div>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="../../assets/js/vendor/popper.min.js"></script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <script src="../../assets/js/vendor/holder.min.js"></script>
    <script>
      Holder.addTheme('thumb', {
        bg: '#55595c',
        fg: '#eceeef',
        text: 'Thumbnail'
      });
    </script>

app/views/events/new.html.erb
<div class="container">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <%= form_for @event do |f| %>
      <% if @event.errors.any? %>
      <h4><%= pluralize(@event.errors.count, "error") %> prevented this message from saving</h4>
        <ul>
          <% @event.errors.full_messages.each do |msg| %>
          <li>
            <%= msg %>
          </li>
            <% end %>
        </ul>
        <% end %>
    <div class="form-group">
        <label>Titre de l'event </label>
        <%= f.text_field :title, class: 'form-control'%>
    </div>
    <div class="form-group">
        <label>Date de l'event</label>
        <%= f.date_field :start_date, class: 'form-control'%>
    </div>
    <div class="form-group">
        <label>Durée de l'event</label>
        <%= f.number_field :duration, class: 'form-control'%>
    </div>
    <div class="form-group">
        <label>Description de l'event</label>
        <%= f.text_area :description, class: 'form-control'%>
    </div>
    <div class="form-group">
        <label>Prix</label>
        <%= f.text_field :price, class: 'form-control'%>
    </div>
    <div class="form-group">
        <label>Localisation</label>
        <%= f.text_field :location, class: 'form-control'%>
    </div>
        <div class="form-group">
        <button type="submit" class="btn btn-primary">Valider</button>
    </div>
    <% end %>
</div>

app/views/events/show.html.erb
<div class="container text-center">
    <div class="cover-container d-flex w-100 p-3 mx-auto flex-column">
        <div class="row">
          <div class="col-md-12">
            <!-- Blog Post -->
            <div class="card mb-4">
              <img class="card-img-top" src="http://placehold.it/750x300" alt="Card image cap">
              <div class="card-body">
                <h2 class="card-title"><%= @event.title%></h2>
                <p class="card-text">Place: <%= @event.location%> | Price: <%= @event.price%> $</p>
                <img class="card-img-top" src="https://picsum.photos/id/<%= rand(1..99) %>/500/230" alt="Card image cap">
                <p class="card-text"><%= @event.description%></p>
                <% if !@event.users.include?(current_user) && current_user != @event.user%>
                  <% if @event.is_free? %>
                      <%= link_to 'Subscribe', event_attendances_path(@event), method: :create, class: "btn btn-primary"%>
                  <% else %>
                      <%= link_to 'Subscribe', new_event_attendance_path(@event), class: "btn btn-primary"%>
                  <% end %>
                <% end %>
                <% if @event.user == current_user%>
                      <%= link_to 'Mon espace Evenement', attendances_path, class: "btn btn-primary"%>
                <% end%>
              </div>
              <div class="card-footer text-muted">
                Takes place on "<%= @event.start_date %>" lasts for <%= @event.duration%> min, Administrated by 
                <%= link_to @event.user.first_name, "/users/#{@event.user.id}" %>
              </div>
            </div>
          </div>
        </div>
    </div>
</div>

app/views/layouts/_header.html.erb
    <nav class="site-header sticky-top py-1">
      <div class="container d-flex flex-column flex-md-row justify-content-between">
        <div class="py-2 d-none d-md-inline-block">
            <%= link_to "Home", '/' %>
            <%= link_to "Create Event", new_event_path %>
        </div>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            User
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <% if user_signed_in? %>
                <div class="dropdown-item"><%= link_to "My profile", user_path(current_user) %></div>
                <div class="dropdown-item" href="#"><%= link_to "Logout", destroy_user_session_path, method: :delete %></div>
            <% else %>
                <div class="dropdown-item" ><%= link_to "Sign in", new_user_session_path %></div>
                <div class="dropdown-item" ><%= link_to "Sign up", new_user_registration_path %></div>
            <% end %>
            </div>
        </li>
      </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Evenbrite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>


    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/product/">


    <link href="/docs/4.5/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/carousel/">

    <!-- Bootstrap core CSS -->
    <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="product.css" rel="stylesheet">
  </head>

  <body>
    <% flash.each do |type, msg| %>
      <div>
        <%= msg %>
      </div>
    <% end %>
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<div class="page-content page-container" id="page-content">
    <div class="padding">
        <div class="row d-flex justify-content-center">
            <div class="col-xl-6 col-md-12">
                <div class="card user-card-full">
                    <div class="row m-l-0 m-r-0">
                        <div class="col-sm-4 bg-c-lite-green user-profile">
                            <div class="card-block text-center text-white">
                                <%if @user.avatar.attached?%>
                                    <div class="m-b-25"> <%= image_tag @user.avatar, alt: 'avatar', class: "img-radius" %> </div>
                                <%else%>
                                    <div class="m-b-25"> <img src="https://img.icons8.com/bubbles/100/000000/user.png" class="img-radius" alt="User-Profile-Image"> </div>
                                <%end%>
                                <h6 class="f-w-600">
                                <%= @user.first_name%> <%= @user.last_name %>
                                </h6>
                                <p>THP Designer</p> <i class=" mdi mdi-square-edit-outline feather icon-edit m-t-10 f-16"></i>
                                <% if current_user == @user %>
                                    <p><%= link_to "(Change my password)", edit_user_registration_path(@user) %></p> <i class=" mdi mdi-square-edit-outline feather icon-edit m-t-10 f-16"></i>
                                    <p> <%= link_to 'Mon espace Evenement', attendances_path %> </p>
                                <% end %>
                            </div>
                        </div>
                        <div class="col-sm-8">
                            <div class="card-block">
                                <h6 class="m-b-20 p-b-5 b-b-default f-w-600">Information</h6>
                                <div class="row">
                                    <div class="col-sm-6">
                                        <p class="m-b-10 f-w-600">Email</p>
                                        <h6 class="text-muted f-w-400"><%= @user.email %></h6>
                                    </div>
                                    <div class="col-sm-6">
                                        <p class="m-b-10 f-w-600">Description</p>
                                        <h6 class="text-muted f-w-400"><%= @user.description %></h6>
                                    </div>
                                </div>
                                <h6 class="m-b-20 m-t-40 p-b-5 b-b-default f-w-600">Projects</h6>
                                <div class="row">
                                    <div class="col-sm-6">
                                        <p class="m-b-10 f-w-600">Event</p>
                                        <% @user.events.each do |e| %>
                                            <h6 class="text-muted f-w-400"><%= e.title %></h6>
                                        <% end %>
                                    </div>
                                    <div class="col-sm-6">
                                        <p class="m-b-10 f-w-600">Most Viewed</p>
                                        <h6 class="text-muted f-w-400">Dinoter husainm</h6>
                                    </div>
                                </div><br>
                                <h6 class="m-b-20 p-b-5 b-b-default f-w-600">Profile picture</h6>
                                <%= form_tag user_avatars_path(@user), multipart: true do %>
                                        <%= file_field_tag :avatar, class: "text-center" %>
                                        <%= submit_tag "mettre à jour" , class: "btn btn-lg btn-primary btn-block" %>
                                    <% end %>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>